function y = IBS_smoothdata(x)
%% Atesh Koul

%  Preprocess input x
%    This function expects an input vector x or a matrix (smoothing done on the cols) 

% Generated by MATLAB(R) 9.8 and Signal Processing Toolbox 8.4.
% Generated on: 18-Jan-2021 14:43:44
tx = linspace(0,120,size(x,1));
y = smoothdata(x,'movmean',1,'SamplePoints',tx);
