function results_smile = IBS_import_smile_detection(filename, dataLines)
%IMPORTFILE Import data from a text file
%  RESULTSSMILEDETECTIONFROMEYETRACKER = IMPORTFILE(FILENAME) reads data
%  from text file FILENAME for the default selection.  Returns the data
%  as a table.
%
%  RESULTSSMILEDETECTIONFROMEYETRACKER = IMPORTFILE(FILE, DATALINES)
%  reads data for the specified row interval(s) of text file FILENAME.
%  Specify DATALINES as a positive scalar integer or a N-by-2 array of
%  positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  resultssmiledetectionfromeyetracker = importfile("D:\iannettilab_dropbox\Dropbox\Koul_Atesh\IBS\Dyd_001\Eye_tracker\pupil_0\FaNoOcc_1\Sub_0\000\exports\000\results_smile_detection_from_eye_tracker.csv", [2, Inf]);
%
%  See also READTABLE.
%  created by: Atesh
%  DATE: 18-Mar-2021
% Auto-generated by MATLAB on 18-Mar-2021 14:33:36

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 15);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VarName1", "time_stamps_raw", "time_stamps_rel", "frame_no", "smile","smile_pca", "mouth_size", "mouth_size_inner", "mouth_size_x", "mouth_size_y", "mouth_size_inner_x", "mouth_size_inner_y", "Dyd_no", "Sub_no", "Condition", "block_Condition"];
opts.VariableTypes = ["char", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "categorical", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "VarName1", "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["VarName1", "Condition"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "block_Condition", "TrimNonNumeric", true);
opts = setvaropts(opts, "block_Condition", "ThousandsSeparator", ",");

% Import the data
results_smile = readtable(filename, opts);

end