function blinks = IBS_import_blink(filename, dataLines)
%IMPORTFILE Import data from a text file
%  BLINKS = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  BLINKS = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  blinks = IBS_import_blink("D:\iannettilab_dropbox\Dropbox\Koul_Atesh\IBS\Dyd_007\Eye_tracker\pupil_1\NeNoOcc_1\Sub_1\000\exports\001\blinks.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 03-Feb-2021 14:30:31

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 10);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["id", "start_timestamp", "duration", "end_timestamp", "start_frame_index", "index", "end_frame_index", "confidence", "filter_response", "base_data"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "char", "char"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["filter_response", "base_data"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["filter_response", "base_data"], "EmptyFieldRule", "auto");

% Import the data
blinks = readtable(filename, opts);

end