function gaze_positions_on_body = IBS_import_gaze_positions_on_body_data(filename, dataLines)
%IMPORTFILE Import data from a text file
%  gaze_positions_on_body = IBS_import_gaze_positions_on_body_data(FILENAME) reads data from
%  text file FILENAME for the default selection.  Returns the data as a
%  table.
%
%  gaze_positions_on_body = IBS_import_gaze_positions_on_body_data(FILE, DATALINES) reads data
%  for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  resultsellipseeyegazeapifull = importfile("D:\iannettilab_dropbox\Dropbox\Koul_Atesh\IBS\Dyd_001\Eye_tracker\pupil_0\FaNoOcc_1\Sub_0\000\exports\000\results_ellipse_eye_gaze_api_full.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 12-Jan-2021 11:10:15

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 12);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VarName1", "analyzed_frame_no", "time_stamps", "valid_trials", "eye_on_body", "eye_on_face", "eye_on_eye", "eye_on_mouth", "eye_on_nose", "eye_on_nose_bot", "eye_on_eye_ellipse", "eye_on_face_ellipse"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
gaze_positions_on_body = readtable(filename, opts);

end