function behav_data = IBS_import_ECG_EDA(filename, datatype,dataLines)
%IMPORTFILE Import data from a text file
%  RESULTSECG0FANOOCC1 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  RESULTSECG0FANOOCC1 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  resultsecg0FaNoOcc1 = importfile("E:\Projects\IBS\Data\Processed\ECG\Dyd_001\results_ecg_0_FaNoOcc_1.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 15-Mar-2021 17:05:05

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 3
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 27);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VarName1", "ECG_Raw", "ECG_Clean", "ECG_Rate", "ECG_Quality", "ECG_R_Peaks", "ECG_P_Peaks", "ECG_Q_Peaks", "ECG_S_Peaks", "ECG_T_Peaks", "ECG_P_Onsets", "ECG_T_Offsets", "ECG_Phase_Atrial", "ECG_Phase_Completion_Atrial", "ECG_Phase_Ventricular", "ECG_Phase_Completion_Ventricular", "EDA_Raw", "EDA_Clean", "EDA_Tonic", "EDA_Phasic", "SCR_Onsets", "SCR_Peaks", "SCR_Height", "SCR_Amplitude", "SCR_RiseTime", "SCR_Recovery", "SCR_RecoveryTime"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "char", "double", "char", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["ECG_Phase_Atrial", "ECG_Phase_Ventricular"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["ECG_Phase_Atrial", "ECG_Phase_Ventricular"], "EmptyFieldRule", "auto");

% Import the data
behav_data = readtable(filename, opts);

end