function video_body_pose = IBS_import_video_landmarks(filename, dataLines)
%IMPORTFILE Import data from a text file
%  RESULTSVIDEO1POSEBODYPROCESSED = IMPORTFILE(FILENAME) reads data from
%  text file FILENAME for the default selection.  Returns the data as a
%  table.
%
%  RESULTSVIDEO1POSEBODYPROCESSED = IMPORTFILE(FILE, DATALINES) reads
%  data for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  resultsvideo1posebodyprocessed = importfile("Z:\Dropbox\Koul_Atesh\IBS\Dyd_001\Video\Ses_001\results_video_1_pose_body_processed.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 16-Jan-2021 15:59:07

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 57);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "Unnamed0", "Nose_x", "Neck_x", "RShoulder_x", "RElbow_x", "RWrist_x", "LShoulder_x", "LElbow_x", "LWrist_x", "MidHip_x", "RHip_x", "RKnee_x", "RAnkle_x", "LHip_x", "LKnee_x", "LAnkle_x", "REye_x", "LEye_x", "REar_x", "LEar_x", "LBigToe_x", "LSmallToe_x", "LHeel_x", "RBigToe_x", "RSmallToe_x", "RHeel_x", "Nose_y", "Neck_y", "RShoulder_y", "RElbow_y", "RWrist_y", "LShoulder_y", "LElbow_y", "LWrist_y", "MidHip_y", "RHip_y", "RKnee_y", "RAnkle_y", "LHip_y", "LKnee_y", "LAnkle_y", "REye_y", "LEye_y", "REar_y", "LEar_y", "LBigToe_y", "LSmallToe_y", "LHeel_y", "RBigToe_y", "RSmallToe_y", "RHeel_y", "VarName53", "VarName54", "Dyd_no", "Sub_no", "Condition"];
opts.SelectedVariableNames = ["Unnamed0", "Nose_x", "Neck_x", "RShoulder_x", "RElbow_x", "RWrist_x", "LShoulder_x", "LElbow_x", "LWrist_x", "MidHip_x", "RHip_x", "RKnee_x", "RAnkle_x", "LHip_x", "LKnee_x", "LAnkle_x", "REye_x", "LEye_x", "REar_x", "LEar_x", "LBigToe_x", "LSmallToe_x", "LHeel_x", "RBigToe_x", "RSmallToe_x", "RHeel_x", "Nose_y", "Neck_y", "RShoulder_y", "RElbow_y", "RWrist_y", "LShoulder_y", "LElbow_y", "LWrist_y", "MidHip_y", "RHip_y", "RKnee_y", "RAnkle_y", "LHip_y", "LKnee_y", "LAnkle_y", "REye_y", "LEye_y", "REar_y", "LEar_y", "LBigToe_y", "LSmallToe_y", "LHeel_y", "RBigToe_y", "RSmallToe_y", "RHeel_y", "VarName53", "VarName54", "Dyd_no", "Sub_no", "Condition"];
opts.VariableTypes = ["char", "char", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "char", "char", "double", "double", "categorical"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Unnamed0", "VarName53", "VarName54"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Unnamed0", "VarName53", "VarName54", "Condition"], "EmptyFieldRule", "auto");

% Import the data
video_body_pose = readtable(filename, opts);

end