function video_hand_pose = IBS_import_video_hand_landmarks(filename, dataLines)
%IMPORTFILE Import data from a text file
%  RESULTSVIDEO1POSEHANDPROCESSED = IMPORTFILE(FILENAME) reads data from
%  text file FILENAME for the default selection.  Returns the data as a
%  table.
%
%  RESULTSVIDEO1POSEHANDPROCESSED = IMPORTFILE(FILE, DATALINES) reads
%  data for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  resultsvideo1posehandprocessed = importfile("D:\iannettilab_dropbox\Dropbox\Koul_Atesh\IBS\Dyd_001\Video\Ses_001\results_video_1_pose_hand_processed.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 24-May-2021 17:34:25

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 90);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VarName1", "Unnamed0", "L_Palm_0_x", "L_Palm_1_x", "L_Thumb_1_x", "L_Thumb_2_x", "L_Thumb_3_x", "L_Index_1_x", "L_Index_2_x", "L_Index_3_x", "L_Index_4_x", "L_Middle_1_x", "L_Middle_2_x", "L_Middle_3_x", "L_Middle_4_x", "L_Ring_1_x", "L_Ring_2_x", "L_Ring_3_x", "L_Ring_4_x", "L_Little_1_x", "L_Little_2_x", "L_Little_3_x", "L_Little_4_x", "R_Palm_0_x", "R_Palm_1_x", "R_Thumb_1_x", "R_Thumb_2_x", "R_Thumb_3_x", "R_Index_1_x", "R_Index_2_x", "R_Index_3_x", "R_Index_4_x", "R_Middle_1_x", "R_Middle_2_x", "R_Middle_3_x", "R_Middle_4_x", "R_Ring_1_x", "R_Ring_2_x", "R_Ring_3_x", "R_Ring_4_x", "R_Little_1_x", "R_Little_2_x", "R_Little_3_x", "R_Little_4_x", "L_Palm_0_y", "L_Palm_1_y", "L_Thumb_1_y", "L_Thumb_2_y", "L_Thumb_3_y", "L_Index_1_y", "L_Index_2_y", "L_Index_3_y", "L_Index_4_y", "L_Middle_1_y", "L_Middle_2_y", "L_Middle_3_y", "L_Middle_4_y", "L_Ring_1_y", "L_Ring_2_y", "L_Ring_3_y", "L_Ring_4_y", "L_Little_1_y", "L_Little_2_y", "L_Little_3_y", "L_Little_4_y", "R_Palm_0_y", "R_Palm_1_y", "R_Thumb_1_y", "R_Thumb_2_y", "R_Thumb_3_y", "R_Index_1_y", "R_Index_2_y", "R_Index_3_y", "R_Index_4_y", "R_Middle_1_y", "R_Middle_2_y", "R_Middle_3_y", "R_Middle_4_y", "R_Ring_1_y", "R_Ring_2_y", "R_Ring_3_y", "R_Ring_4_y", "R_Little_1_y", "R_Little_2_y", "R_Little_3_y", "R_Little_4_y", "Dyd_no", "Sub_no", "Condition", "Condition_block"];
opts.VariableTypes = ["double", "char", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "categorical", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Unnamed0", "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Unnamed0", "Condition"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "Condition_block", "TrimNonNumeric", true);
opts = setvaropts(opts, "Condition_block", "ThousandsSeparator", ",");

% Import the data
video_hand_pose = readtable(filename, opts);

end