function gaze_nose_dist = IBS_import_gaze_nose_dist(filename, dataLines)
%IMPORTFILE Import data from a text file
%  RESULTSELLIPSEEYEGAZEAPIFULLGAZENOSEDISTANCE = IMPORTFILE(FILENAME)
%  reads data from text file FILENAME for the default selection.
%  Returns the data as a table.
%
%  RESULTSELLIPSEEYEGAZEAPIFULLGAZENOSEDISTANCE = IMPORTFILE(FILE,
%  DATALINES) reads data for the specified row interval(s) of text file
%  FILENAME. Specify DATALINES as a positive scalar integer or a N-by-2
%  array of positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  resultsellipseeyegazeapifullgazenosedistance = importfile("D:\iannettilab_dropbox\Dropbox\Koul_Atesh\IBS\Dyd_001\Eye_tracker\pupil_0\FaNoOcc_1\Sub_0\000\exports\000\results_ellipse_eye_gaze_api_full_gaze_nose_distance.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 15-Apr-2021 16:57:41

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 9);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VarName1", "analyzed_frame_no", "time_stamps", "valid_trials", "eye_gaze_distance", "eye_gaze_distance_x", "eye_gaze_distance_y", "data_ts", "data_ts_rel"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
gaze_nose_dist = readtable(filename, opts);

end