function data_breath = IBS_import_resp(filename, dataLines)
%IMPORTFILE Import data from a text file
%  RESULTSRESP0FANOOCC1 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  RESULTSRESP0FANOOCC1 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  resultsresp0FaNoOcc1 = importfile("E:\Projects\IBS\Data\Processed\ECG\Dyd_001\results_resp_0_FaNoOcc_1.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 22-Oct-2021 15:23:03

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 9);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VarName1", "RSP_Raw", "RSP_Clean", "RSP_Amplitude", "RSP_Rate", "RSP_Phase", "RSP_Phase_Completion", "RSP_Peaks", "RSP_Troughs"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "char", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "RSP_Phase", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "RSP_Phase", "EmptyFieldRule", "auto");

% Import the data
data_breath = readtable(filename, opts);

end